dist: trusty
git:
  depth: false
addons:
  sonarcloud:
    organization: "gbrltv"
    token:
	secure: "A6TneLJRVcaFhlgCzsES5m3gnL0Buza2PMDYQSUF5TFgaCJ38CrQejSLgBMug+xh/BfFQJzuSCZWTFvaa8f++vo1YUgRp5S5KpZwgnEvgaqFVyNgmJoRNA6Jqq4ehdG1/8kmD7pX0Aj1REniX8WGgGCGGbEadjIU0NDtxeRI4pJir4/Km9UKLTGJu0Vmm4VoZJ9FPQqLRElrj0sIhI5Lbmdq8qCoTLynEBeHW/2Nm/LbkDH+3QbeK4EFVSKwFQtFD9BeDntNEUn9s9RzWp2YCBSoa8Pq6/IfdgWxchicvWWcAw7rYw3VLHH/AAI06OObvfN/sovJNCSvKE3O+c3YkJpYvQ07yLmd1dWB2qpDgK616PJRpm6f6z4jwFSTMbYMVh/aEcPZ+YLcFi3+L+RDNlJuKN/ymyDkl5SCQqWvoFM0KfUtRyKv3lQFL8z+Apq6NNYKelgoFDM9pUqOxu6IAMfqipeYvnkov5pd1rD4yZzZVx2cNOTehMgz2z8aZE4gVXZntXsVxziFlpyMxrIHLhBvkCNqOoCW5rURhkIwd67imuoM5mxXDFSZrr/wVSHBEwTuzyVfdTuF6kjgXZVUBfQcT2xQPZ1afK3Un+rOCcekLEYEqjjmlCzWtbfJdMhugPFBvWFlTRuzhdMayuzKsNwKYpzb9ZI/ThPDfkLS6M0="

language: python
python:
- '3.6'
before_install:
  - pip install --upgrade pytest
install:
- pip install .[test]
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
script:
- rm -rf .coverage
- coverage erase
- pytest --cov=cdesf2 --cov-report xml:coverage.xml 
- coverage combine --append || true
- coverage report
- coverage xml
- 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then sonar-scanner; fi' # sonar only on non-PRs

after_success:
  - coveralls
  - python-codacy-coverage -r coverage.xml
